import React from "react";

import { Montserrat } from "next/font/google";
import { ThemeProvider } from "./theme-prodiver";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import "./globals.css";

export const font = Montserrat({
  weight: ["200", "400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-50 dark:bg-[#0d1117] duration-config">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <main className={font.className}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
